name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base
        uses: actions/checkout@v5
        if: ${{ github.base_ref }}
        with:
          path: base/
          ref: ${{ github.base_ref }}

      - name: Checkout head
        uses: actions/checkout@v5
        with:
          path: head/

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable
          cache-dependency-path: |
            base/go.sum
            head/go.sum

      - name: Generate code
        run: |
          set -eu

          (cd head && go generate ./...)
          if [ -d base ]; then
            (cd base && go generate ./...)
          fi

      - name: Create benchmarks result directory
        run: mkdir -p benchmarks/

      - name: Run benchmarks against base
        if: ${{ github.base_ref }}
        run: go test -count=10 -benchtime 10s -bench=. -run=^$ -benchmem ./... | tee ../benchmarks/base.txt
        working-directory: base

      - name: Run benchmarks against head
        run: go test -count=10 -benchtime 10s -bench=. -run=^$ -benchmem ./... | tee ../benchmarks/head.txt
        working-directory: head

      - name: Install benchstat
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Generate report
        if: ${{ ! github.base_ref }}
        run: |
          set -eu
          benchstat benchmarks/head.txt | tee ./benchmarks/stats.txt

          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## Benchmarks

          ### Statistics

          \`\`\`
          $(cat benchmarks/stats.txt)
          \`\`\`

          ### Results

          \`\`\`
          $(cat benchmarks/head.txt)
          \`\`\`
          EOF

      - name: Compare benchmarks
        if: ${{ github.base_ref }}
        run: |
          set -eu
          benchstat base=benchmarks/base.txt head=benchmarks/head.txt | tee ./benchmarks/diff.txt

          cat << EOF >> $GITHUB_STEP_SUMMARY
          ## Benchmarks

          ### Difference

          \`\`\`
          $(cat benchmarks/diff.txt)
          \`\`\`

          ### Head

          \`\`\`
          $(cat benchmarks/base.txt)
          \`\`\`

          ### Base

          \`\`\`
          $(cat benchmarks/head.txt)
          \`\`\`
          EOF

      - uses: actions/upload-artifact@v5
        with:
          name: benchmarks
          path: benchmarks/*
          if-no-files-found: error
